#!/usr/bin/env bash
cat <<EOF | xargs chmod +x
admin/prepare-release
admin/build-docs
admin/fixperms
admin/runtests
examples/consumer.rb
EOF

find "examples/rails_server/script/" -type f | xargs chmod +x
