#!/usr/bin/env bash
#
# Prepare this repository for release
#
# required tools:
#  rdoc
#  darcs

set -e

HERE=$(readlink --canonicalize $(dirname "$0"))
ROOT=$(dirname "$HERE")

cd "$ROOT"

# set permissions
bash ./admin/fixperms

# build documentation
./admin/build-docs

# build changelog
darcs changes --from-tag . --summary > CHANGELOG

